name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libudev-dev libgl1-mesa-dev

    - name: Setup Conan and Build
      run: |
        pip install conan
        conan profile detect --force
        echo "[settings]
        arch=x86_64
        build_type=Release
        compiler=gcc
        compiler.version=11
        compiler.libcxx=libstdc++11
        compiler.cppstd=17
        os=Linux
        [conf]
        tools.system.package_manager:mode=install" > ~/.conan2/profiles/default
        conan install . --output-folder=build --build=missing -c tools.system.package_manager:mode=install
        cd build
        cmake .. -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" -DCMAKE_BUILD_TYPE=Release
        cmake --build .