name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install base dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential pkg-config libudev-dev

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install and setup Conan
      run: |
        python -m pip install --upgrade pip setuptools
        pip install conan
        conan profile detect --force

    - name: Install dependencies with Conan
      run: |
        conan install . --output-folder=build --build=missing -c tools.system.package_manager:mode=install

    - name: Build
      run: |
        cd build
        cmake .. -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" -DCMAKE_BUILD_TYPE=Release
        cmake --build .