name: Build Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get install -y build-essential cmake libudev-dev libgl1-mesa-dev \
        libx11-dev libx11-xcb-dev libfontenc-dev libice-dev libsm-dev libxau-dev \
        libxaw7-dev libxcb-glx0-dev libxcb-render0-dev libxcb-render-util0-dev \
        libxcb-xkb-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-keysyms1-dev \
        libxcb-randr0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev \
        libxcb-xinerama0-dev libxcb-dri3-dev libxcb-cursor-dev libxcb-composite0-dev \
        libxcb-ewmh-dev libxcb-present-dev libxcb-res0-dev xorg-dev

    - name: Setup Conan and Build
      run: |
        pip install conan==2.0.10
        conan profile detect
        conan install . --output-folder=build --build=missing -c tools.system.package_manager:mode=install
        cd build
        cmake .. -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" -DCMAKE_BUILD_TYPE=Release
        cmake --build .