name: CMake with Conan on Linux

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]

    steps:
    - uses: actions/checkout@v4

    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential \
          libudev-dev \
          libx11-dev \
          libxrandr-dev \
          libxcursor-dev \
          libxi-dev \
          libopenal-dev \
          libasound2-dev \
          libgl1-mesa-dev

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install and Configure Conan
      run: |
        python -m pip install --upgrade pip
        pip install conan
        conan profile detect --force
        conan config install https://github.com/conan-io/conancenter-index.git

    - name: Install Dependencies with Conan
      run: |
        conan install . --output-folder=build --build=missing -c tools.system.package_manager:mode=install

    - name: Configure CMake
      run: |
        cd build
        cmake .. -G "Unix Makefiles" -DCMAKE_TOOLCHAIN_FILE="conan_toolchain.cmake" -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}

    - name: Build
      run: |
        cd build
        cmake --build . --config ${{ matrix.build_type }}