name: Build and Test
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-venv libudev-dev libgl1-mesa-dev
        python3 -m venv venv
        source venv/bin/activate
        pip install conan==2.0.17
    - name: Build
      run: |
        source venv/bin/activate
        conan profile detect --force && conan install . --output-folder=build --build=missing && cd build && cmake .. -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake -DCMAKE_BUILD_TYPE=Release && cmake --build .
    - name: Build package
      run: cd build && cpack