name: Build and Test
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-venv libudev-dev libgl1-mesa-dev libsfml-dev
    - name: Setup Python venv and install Conan
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install conan==2.0.17
        conan profile detect --force
    - name: Build
      run: |
        source venv/bin/activate
        cd build 
        cmake .. -DCMAKE_BUILD_TYPE=Release 
        cmake --build .
    - name: Build package
      run: |
        source venv/bin/activate
        cd build && cpack