name: Doxygen Documentation

on:
  push:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'includes/**'
      - 'docs/**'
      - 'Doxyfile'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'src/**'
      - 'includes/**'
      - 'docs/**'
      - 'Doxyfile'
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Doxygen
      run: |
        sudo apt-get update
        sudo apt-get install -y doxygen graphviz

    - name: Generate Documentation
      run: doxygen Doxyfile

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/html
        enable_jekyll: false
        full_commit_message: 'docs: update documentation'